### ISSUE TITLE
yagocd throwing invalid syntax in Red Hat 4.4.7-11 with python 2.6.6

### ISSUE THREAD

**Issue by vamsilella** [grundic/yagocd#9]
Hey i have installed yagocd using pip on my mac and linux. its working fine in mac but not on linux

error:
-------
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from yagocd import Yagocd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/yagocd/__init__.py", line 30, in <module>
    from yagocd.client import Yagocd
  File "/usr/lib/python2.6/site-packages/yagocd/client.py", line 33, in <module>
    from yagocd.resources.agent import AgentManager
  File "/usr/lib/python2.6/site-packages/yagocd/resources/agent.py", line 32, in <module>
    from yagocd.resources.job import JobInstance
  File "/usr/lib/python2.6/site-packages/yagocd/resources/job.py", line 30, in <module>
    from yagocd.resources.artifact import ArtifactManager
  File "/usr/lib/python2.6/site-packages/yagocd/resources/artifact.py", line 136
    parameters = {p: self._require_param(p, func_args) for p in self.PATH_PARAMETERS}
                                                         ^
SyntaxError: invalid syntax

I think yagocd works for python 2.6.6 as well right?

**Comment by vamsilella** [comment]
hmmm figured out that this module doesn't work with python2.6
i have upgraded to python 2.7 and its working.
